// <auto-generated />
namespace NEWS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addprop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addprop));
        
        string IMigrationMetadata.Id
        {
            get { return "201806012014311_add prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
