//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string Caption { get; set; }
        public string FileName { get; set; }
        public long PostGalleryID { get; set; }
    
        public virtual PostGallery PostGallery { get; set; }
    }
}
